language: php
php:
  - '5.4'
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
cache:
  directories:
    - $HOME/.composer/cache
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml